### ISSUE TITLE
FIX-gamefield-toJSON-method

### ISSUE THREAD

**Issue by Dawinartor** [Dawinartor/Minesweaper#11]
Python lint says that when I use the toJSON() method, I get a string instead of a JSON object. However, the return value must be a JSON object.

![image](https://user-images.githubusercontent.com/46395323/148761266-1c55a7c5-0667-4dbe-b48e-aea92309eca7.png)

**Comment by memo1918** [comment]
did you try js side?

**Comment by Dawinartor** [comment]
#

> did you try js side?

Yes and I was not able to access the JSON information like we talked about it.

```
# what I tried
gameJSON.Gamefield[0].x
```

**Comment by memo1918** [comment]
you just have to JSON.parse() it before using it
and it works
![image](https://user-images.githubusercontent.com/52012349/148762851-3da94518-3e75-4a92-9d7c-6aff83e4bb22.png)

**Comment by Dawinartor** [comment]
Thanks, but this is your solution still?

**Comment by Dawinartor** [comment]
> you just have to JSON.parse() it before using it and it works ![image](https://user-images.githubusercontent.com/52012349/148762851-3da94518-3e75-4a92-9d7c-6aff83e4bb22.png)

Thanks, but this is your solution still?

**Comment by memo1918** [comment]
I don't understant, what do you mean still ?. Right now you can acces JSON. If you have other demands please create another issue and close this one.

**Comment by Dawinartor** [comment]
> I don't understant, what do you mean still ?. Right now you can acces JSON. If you have other demands please create another issue and close this one.

Sure. 
You are right.
