### ISSUE TITLE
add-attribute-tileNumber-to-tile-class

### ISSUE THREAD

**Issue by Dawinartor** [Dawinartor/Minesweaper#13]
I faced the problem to need the tile number I click on to get all the values inside the specific tile. <br>
Please extend the tile class with the following:

- [x] Add private attribute tileNumber
- [x] Add all needed methods for tileNumber to get the informations about it
- [x] Extend tileNumber in Gamefield.toJSON()

**Comment by memo1918** [comment]
tileNumber will be renamed as a tileIndex
